version: '3.8'

services:

  #База данных
  database:
    image: mysql
    container_name: database_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
    volumes:
      - database_mysql:/data/db
    networks:
      - marketplace_network
  #Управление СУБД
  phpmyadmin:
    image: phpmyadmin:5.1-apache
    container_name: db_cp_phpmyadmin
    restart: unless-stopped
    ports:
    - "8080:80"
    environment:
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - PMA_ARBITRARY=1
    networks:
      - marketplace_network
  #Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: backend_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/extra_conf/mime.types:/etc/nginx/extra_conf/mime.types
      - ./nginx/extra_conf/proxy.conf:/etc/nginx/extra_conf/proxy.conf
      - ./nginx/extra_conf/error.log:/etc/nginx/logs/error.log
    networks:
      - marketplace_network
  #Основной бек
  backend:
    build: ./backend
    container_name: backend_main
    restart: unless-stopped
    command: npm run start:dev
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - PORT=9999
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASS
      - DB_TITLE=marketplace
    networks:
      - marketplace_network

volumes:
  database_mysql:

networks:
  marketplace_network:
    driver: bridge
